[package]
name = "rendering-shaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }
